version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: mes-db-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mes_user
      POSTGRES_PASSWORD: mes_password
      POSTGRES_DB: mes_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: mes-cache-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
